export class Cp2020VehicleTypes {
  static types: Array<string> = [
    'Motorcycle',
    'Car',
    'Pick-up',
    'Truck',
    'Boat',
    'APC',
    'APC Wheeled',
    'APC Tracked',
    'IFV',
    'IFV Wheeled',
    'IFV Tracked',
    'Main Battle Tank',
    'Hover',
    'Light Helicopter',
    'Medium Helicopter',
    'Heavy Helicopter',
    'AV',
    'Osprey',
    'Ultralight',
    'Light Airplane',
    'Medium Airplane',
    'Heavy Airplane',
    'Small Jet',
    'Large Jet',
    'Airship',
    'Submarine',
    'Cyberwalk',
    'Cyberwalk-Biped',
    'Super-Heavy Construction'
  ];
}
