export enum NrMapDefaults {
  GRID_SIZE = 34,
  ROWS_MIN = 10,
  ROWS_DEFAULT = 15,
  COLUMNS_DEFAULT = 15,
  COLUMNS_MIN = 10,
  CPU_MIN = 2,
  CPU_MAX = 7,
  DATAWALL_STR_MIN = 1,
  DATAWALL_STR_MAX = 10,
  CODEGATE_STR_MIN = 2,
  CODEGATE_STR_MAX = 10,
  SKILL_MIN = 4,
  SKILL_MAX = 10

}
