export enum Cp2020EquipmentActionTypes {
  ADD_EQUIPMENT = '[CP2020_EQUIPMENT_STORE] Add',
  REMOVE_EQUIPMENT = '[CP2020_EQUIPMENT_STORE] Remove',
  UPDATE_EQUIPMENT = '[CP2020_EQUIPMENT_STORE] Update',
  LOAD_DATA = '[CP2020_EQUIPMENT_STORE] Load',
  LOAD_DATA_SUCCESS = '[CP2020_EQUIPMENT_STORE] Load Success',
  LOAD_DATA_FAILURE = '[CP2020_EQUIPMENT_STORE] Load Failure',
}
